# Generated by Django 4.0.4 on 2022-05-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('volume', models.FloatField()),
                ('consist', models.TextField()),
                ('image_url', models.TextField(default='')),
                ('price_in_rub', models.IntegerField(default=0)),
            ],
        ),
    ]
