# Generated by Django 4.0.4 on 2022-05-19 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_products_consumer_consumer_products'),
        ('factory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='user.consumer'),
        ),
    ]
