# Generated by Django 4.0.4 on 2022-05-19 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_consumer_consumer_products'),
        ('factory', '0003_alter_product_consumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.consumer'),
        ),
    ]
