# Generated by Django 4.0.4 on 2022-05-19 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_consumer_products'),
        ('factory', '0004_alter_product_consumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumers_products', to='user.consumer'),
        ),
    ]
