# Generated by Django 4.0.4 on 2022-05-17 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0001_initial'),
        ('user', '0001_initial'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='user.client'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_service', to='user.deliveryservice'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_of_products', to='factory.product'),
        ),
        migrations.AddField(
            model_name='deliveryman',
            name='orders_list',
            field=models.ManyToManyField(blank=True, related_name='delivery_man_orders', to='delivery.order'),
        ),
    ]
