# Generated by Django 4.0.4 on 2022-05-23 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_consumer_products'),
        ('delivery', '0004_alter_order_delivery_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_service', to='user.deliveryservice'),
        ),
    ]
