# Generated by Django 4.0.4 on 2022-05-23 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_client_orders'),
        ('delivery', '0005_alter_order_delivery_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='user.client'),
        ),
    ]
