# Generated by Django 4.0.4 on 2022-05-23 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0005_alter_product_consumer'),
        ('delivery', '0007_alter_order_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='factory.product'),
        ),
    ]
