# Generated by Django 4.0.4 on 2022-05-25 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_deliveryservice_orders_list_and_more'),
        ('delivery', '0008_alter_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryman',
            name='delivery_service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_men', to='user.deliveryservice'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to='user.client'),
        ),
    ]
