# Generated by Django 4.0.4 on 2022-05-25 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_client_orders'),
        ('delivery', '0009_deliveryman_delivery_service_alter_order_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_service',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_man',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_man', to='user.deliveryservice'),
        ),
    ]
