# Generated by Django 4.0.4 on 2022-05-25 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_alter_order_delivery_man'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryman',
            name='orders_list',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_man',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_list', to='delivery.deliveryman'),
        ),
    ]
