# Generated by Django 4.0.4 on 2022-05-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_remove_deliveryman_orders_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryman',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
