# Generated by Django 4.0.4 on 2022-05-26 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_client_orders'),
        ('delivery', '0013_deliveryman_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='user.deliveryservice'),
        ),
    ]
