# Generated by Django 4.0.4 on 2022-05-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_consumer_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumer',
            old_name='products',
            new_name='consumer_products',
        ),
    ]
