# Generated by Django 4.0.4 on 2022-05-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_alter_product_consumer'),
        ('user', '0003_rename_products_consumer_consumer_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='consumer_products',
            field=models.ManyToManyField(blank=True, related_name='products', to='factory.product'),
        ),
    ]
