# Generated by Django 4.0.4 on 2022-05-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0004_alter_product_consumer'),
        ('user', '0005_alter_consumer_consumer_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='consumer_products',
        ),
        migrations.AddField(
            model_name='consumer',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products', to='factory.product'),
        ),
    ]
