# Generated by Django 4.0.4 on 2022-05-19 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_consumer_consumer_products_consumer_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='products',
        ),
    ]
