# Generated by Django 4.0.4 on 2022-05-23 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_consumer_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='orders',
        ),
    ]
