# Generated by Django 4.0.4 on 2022-05-25 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_client_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryservice',
            name='orders_list',
        ),
        migrations.RemoveField(
            model_name='deliveryservice',
            name='workers_list',
        ),
    ]
