# Generated by Django 4.0.4 on 2022-05-25 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_deliveryman_delivery_service_alter_order_client'),
        ('user', '0009_remove_deliveryservice_orders_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to='delivery.order'),
        ),
    ]
